version: '3'
services:
  #MySQL Service
  db:
    image: mysql:5.7.22
    container_name: db
    restart: unless-stopped
    tty: true
    ports:
      - "3306:3306"
    environment:
      - MYSQL_DATABASE=shop
      - MYSQL_ROOT_PASSWORD=thoaiky1992
      - SERVICE_TAGS=dev
      - SERVICE_NAME=mysql
    volumes:
      - dbdata:/var/lib/mysql/
    networks:
      - app-network
  #Phpmyadmin
  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - '7000:80'
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: thoaiky1992 
    networks:
      - app-network

#Docker Networks
networks:
  app-network:
    driver: bridge
#Volumes
volumes:
  dbdata:
    driver: local